version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:16
    steps:
      - node/install
      - checkout
      - aws-cli/setup
# Installing the frontend dependencies
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
            npm install webpack@latest --save-dev
      # - run:
      #     name: Front-End Tests
      #     command: |
      #       npm run frontend:test
      # - run:
      #     name: Front-End End-to-end Testing
      #     command: |
      #       npm run frontend:e2e

# Building the frontend
      - run:
          name: Front-End Build
          command: |
            NODE_OPTIONS=--openssl-legacy-provider npm run frontend:build
# Deploying the frontend to AWS S3
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
# Installing the Backend dependencies
      - run:
          name: Back-End Install
          command: |
            npm run api:install
# Changing the main entry point in package.json for the Backend
      # - run:
      #     name: Back-End Change Main Entry Point
      #     command: |
      #       npm run backend:change-main
# Building the backend
      - run:
          name: Back-End Build
          command: |
            npm run api:build
# Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb

      - run:
          name: Initialize Elastic Beanstalk
          command: |
            eb init -p node.js udagram-api \
              --region us-east-1 \
              --platform node.js
              
            # Set the default environment
            eb use Udagram-api-env
      - run:
          name: Seting Environment Variables in Elastic BeanstalkUsing eb setenv commaned
          command: |
            EB_ENV_VARS=$(env | grep CIRCLE | awk -F "=" '{print $1"="$2}' | tr '\n' ' ')
            eb setenv $EB_ENV_VARS
# Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run api:deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - master
